version: "3.8"

services:
  chromium:
    image: linuxserver/chromium:latest
    container_name: chromium
    environment:
      - PUID=1000        # 宿主机用户ID，推荐设置为你自己的UID
      - PGID=1000        # 宿主机用户组ID
      - TZ=Asia/Shanghai # 时区
      - LANGUAGE=zh_CN:zh
      - LANG=zh_CN.UTF-8
      - LANG=C.UTF-8  # 设置本地语言为"C.UTF-8",让KasmVNC支持中文输入
    volumes:
      - ./config:/config # 配置文件挂载目录
      - ./fonts:/usr/share/fonts  # 配置本地中文字体挂载，解决chromium浏览器中文无法显示的问题
      - /var/run/docker.sock:/var/run/docker.sock  # 挂载docker.sock配置文件
    ports:
      - 3010:3000        # WebUI (noVNC)
      - 3011:3001        # VNC 端口
    shm_size: "1gb"      # 共享内存大小，避免浏览器崩溃
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined # 支持沙箱测试模式
